[versions]
# Build details
compileSdk = "35"
targetSdk = "35"
minSdk = "26"
versionCode = "39"
versionName = "2.1.6"

# Libraries
composeBom = "2025.02.00"
firebaseBom = "33.10.0"

accompanistPermissions = "0.37.2"
androidCredentials = "1.5.0-rc01"
androidLifecycle = "2.8.7"
androidMedia = "1.5.1"
androidTestEspresso = "3.6.1"
androidTestJunit = "1.2.1"
coil = "2.7.0"
composeNavigation = "2.8.8"
googleid = "1.1.1"
haze = "1.3.1"
junit = "4.13.2"
koin = "4.0.2"
kotlinCore = "1.15.0"
kotlinSerializationJson = "1.8.0"
ktor = "3.1.0"
mapsCompose = "6.4.2"
playServicesLocation = "21.3.0"
playServicesMaps = "19.1.0"

# Plugins
androidGradlePlugin = "8.8.2"
googleMapsplatformPlugin = "2.0.1"
googleServicesPlugin = "4.4.2"
kotlinPlugins = "2.1.10"
ktlintPlugin = "12.2.0"

[libraries]
android-credentials-base = { group = "androidx.credentials", name = "credentials", version.ref = "androidCredentials" }
android-credentials-services = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "androidCredentials" }
android-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidLifecycle" }
android-media-common = { group = "androidx.media3", name = "media3-common", version.ref = "androidMedia" }
android-media-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "androidMedia" }
android-media-session = { group = "androidx.media3", name = "media3-session", version.ref = "androidMedia" }
android-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidTestEspresso" }
android-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidTestJunit" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-ui-base = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling-base = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
google-libraries-googleid = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleid" }
google-libraries-maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "mapsCompose" }
google-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
google-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
haze-base = { group = "dev.chrisbanes.haze", name = "haze", version.ref = "haze" }
haze-materials = { group = "dev.chrisbanes.haze", name = "haze-materials", version.ref = "haze" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-compose-base = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
koin-compose-navigation = { group = "io.insert-koin", name = "koin-androidx-compose-navigation", version.ref = "koin" }
kotlin-core = { group = "androidx.core", name = "core-ktx", version.ref = "kotlinCore" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJson" }
ktor-client-android = { group = "io.ktor", name = "ktor-client-android", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
google-mapsplatform = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "googleMapsplatformPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugins" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinPlugins" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugins" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }
